version: '3'

volumes:
  stellar_burgers_static:

services:
  frontend:
    container_name: stellar_burgers_frontend
    image: kaleontyev/stellar_burgers_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - stellar_burgers_static:/frontend_static

  gateway:
    container_name: stellar_burgers_gateway
    image: kaleontyev/stellar_burgers_gateway
    depends_on:
      - frontend
    ports:
      - 7000:80
    volumes:
      - stellar_burgers_static:/staticfiles
