version: '3'

volumes:
  static:

services:
  frontend:
    container_name: frontend
    image: kaleontyev/stellar_burgers_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    container_name: gateway
    image: kaleontyev/stellar_burgers_gateway
    depends_on:
      - frontend
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles
